# Generated by Django 4.1.1 on 2022-10-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombres",
                    models.CharField(max_length=50, verbose_name="Nombres del Autor"),
                ),
                (
                    "apellidos",
                    models.CharField(max_length=50, verbose_name="Apellidos del Autor"),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, null=True, verbose_name="Twitter"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                ("web", models.URLField(blank=True, null=True, verbose_name="Web")),
                (
                    "correo",
                    models.EmailField(
                        max_length=254, verbose_name="Correo electronico"
                    ),
                ),
                (
                    "estado",
                    models.BooleanField(
                        default=True, verbose_name="Autor Activo/Autor no Activo"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="Nombre de la categoria"
                    ),
                ),
                (
                    "estado",
                    models.BooleanField(
                        default=True,
                        verbose_name="Categoria Activada/Categoria no Activada",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
    ]
