# Generated by Django 4.1.1 on 2022-10-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_contenido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=100, verbose_name="Slug"),
        ),
    ]
